
// This file has been generated by the GUI designer. Do not modify.
namespace VideoPlayer
{
	public partial class FileSelectionView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label messageLabel;

		private global::Gtk.Button savebutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VideoPlayer.FileSelectionView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VideoPlayer.FileSelectionView";
			// Container child VideoPlayer.FileSelectionView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.messageLabel = new global::Gtk.Label ();
			this.messageLabel.Name = "messageLabel";
			this.messageLabel.LabelProp = "message";
			this.vbox1.Add (this.messageLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.messageLabel]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.savebutton = new global::Gtk.Button ();
			this.savebutton.CanFocus = true;
			this.savebutton.Name = "savebutton";
			this.savebutton.UseUnderline = true;
			this.savebutton.BorderWidth = ((uint)(27));
			this.savebutton.Label = "open";
			this.vbox1.Add (this.savebutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.savebutton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
