
// This file has been generated by the GUI designer. Do not modify.
namespace VideoPlayer
{
	public partial class VideoPlayerView
	{
		private global::VAS.UI.VideoPlayerView videoplayerview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VideoPlayer.VideoPlayerView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VideoPlayer.VideoPlayerView";
			// Container child VideoPlayer.VideoPlayerView.Gtk.Container+ContainerChild
			this.videoplayerview1 = new global::VAS.UI.VideoPlayerView ();
			this.videoplayerview1.Events = ((global::Gdk.EventMask)(256));
			this.videoplayerview1.Name = "videoplayerview1";
			this.Add (this.videoplayerview1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
