
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Component
{
	public partial class HotkeysConfigurationView
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Table table;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Component.HotkeysConfigurationView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.Component.HotkeysConfigurationView";
			// Container child VAS.UI.Component.HotkeysConfigurationView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.vbox2.Add (this.combobox1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.combobox1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(30));
			this.table.BorderWidth = ((uint)(20));
			this.vbox2.Add (this.table);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table]));
			w2.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
