
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.UI.Component
{
	public partial class ImagePreviewWidget
	{
		private global::Gtk.VBox fieldvbox;

		private global::Gtk.Frame fieldframe;

		private global::Gtk.Alignment fieldalignment;

		private global::Gtk.EventBox fieldeventbox;

		private global::Gtk.VBox vbox12;

		private global::VAS.UI.Helpers.ImageView image;

		private global::Gtk.Label imageTitleLabel;

		private global::Gtk.Label label2;

		private global::Gtk.Button resetbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.UI.Component.ImagePreviewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.UI.Component.ImagePreviewWidget";
			// Container child VAS.UI.UI.Component.ImagePreviewWidget.Gtk.Container+ContainerChild
			this.fieldvbox = new global::Gtk.VBox ();
			this.fieldvbox.Name = "fieldvbox";
			this.fieldvbox.Spacing = 6;
			// Container child fieldvbox.Gtk.Box+BoxChild
			this.fieldframe = new global::Gtk.Frame ();
			this.fieldframe.Name = "fieldframe";
			this.fieldframe.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child fieldframe.Gtk.Container+ContainerChild
			this.fieldalignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.fieldalignment.Name = "fieldalignment";
			// Container child fieldalignment.Gtk.Container+ContainerChild
			this.fieldeventbox = new global::Gtk.EventBox ();
			this.fieldeventbox.Name = "fieldeventbox";
			// Container child fieldeventbox.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 2;
			// Container child vbox12.Gtk.Box+BoxChild
			this.image = new global::VAS.UI.Helpers.ImageView ();
			this.image.WidthRequest = 71;
			this.image.HeightRequest = 50;
			this.image.Name = "image";
			this.vbox12.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.imageTitleLabel = new global::Gtk.Label ();
			this.imageTitleLabel.Name = "imageTitleLabel";
			this.imageTitleLabel.LabelProp = global::VAS.Core.Catalog.GetString ("<span font_desc=\"10\">Field</span>");
			this.imageTitleLabel.UseMarkup = true;
			this.imageTitleLabel.Wrap = true;
			this.imageTitleLabel.Justify = ((global::Gtk.Justification)(2));
			this.vbox12.Add (this.imageTitleLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.imageTitleLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::VAS.Core.Catalog.GetString ("<span font_desc=\"8\">click to change...</span>");
			this.label2.UseMarkup = true;
			this.vbox12.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.fieldeventbox.Add (this.vbox12);
			this.fieldalignment.Add (this.fieldeventbox);
			this.fieldframe.Add (this.fieldalignment);
			this.fieldvbox.Add (this.fieldframe);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.fieldvbox [this.fieldframe]));
			w7.Position = 0;
			// Container child fieldvbox.Gtk.Box+BoxChild
			this.resetbutton = new global::Gtk.Button ();
			this.resetbutton.CanFocus = true;
			this.resetbutton.Name = "resetbutton";
			this.resetbutton.UseUnderline = true;
			this.resetbutton.Label = global::VAS.Core.Catalog.GetString ("Reset");
			this.fieldvbox.Add (this.resetbutton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.fieldvbox [this.resetbutton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.fieldvbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
