
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Dialog
{
	public partial class EditPlaylistElementProperties
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Table nametable;

		private global::Gtk.Label label1;

		private global::Gtk.Entry nameentry;

		private global::Gtk.Table slidetable;

		private global::Gtk.SpinButton durationspinbutton;

		private global::Gtk.Label label6;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Dialog.EditPlaylistElementProperties
			this.Name = "VAS.UI.Dialog.EditPlaylistElementProperties";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child VAS.UI.Dialog.EditPlaylistElementProperties.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.nametable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.nametable.Name = "nametable";
			this.nametable.RowSpacing = ((uint)(6));
			this.nametable.ColumnSpacing = ((uint)(6));
			// Container child nametable.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::VAS.Core.Catalog.GetString ("Name");
			this.label1.UseMarkup = true;
			this.nametable.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.nametable [this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(0));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child nametable.Gtk.Table+TableChild
			this.nameentry = new global::Gtk.Entry ();
			this.nameentry.WidthRequest = 76;
			this.nameentry.CanFocus = true;
			this.nameentry.Name = "nameentry";
			this.nameentry.IsEditable = true;
			this.nameentry.InvisibleChar = '●';
			this.nametable.Add (this.nameentry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.nametable [this.nameentry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.nametable);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.nametable]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.slidetable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.slidetable.Name = "slidetable";
			this.slidetable.RowSpacing = ((uint)(6));
			this.slidetable.ColumnSpacing = ((uint)(6));
			// Container child slidetable.Gtk.Table+TableChild
			this.durationspinbutton = new global::Gtk.SpinButton (1D, 100D, 1D);
			this.durationspinbutton.CanFocus = true;
			this.durationspinbutton.Name = "durationspinbutton";
			this.durationspinbutton.Adjustment.PageIncrement = 10D;
			this.durationspinbutton.ClimbRate = 1D;
			this.durationspinbutton.Numeric = true;
			this.durationspinbutton.Value = 1D;
			this.slidetable.Add (this.durationspinbutton);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.slidetable [this.durationspinbutton]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child slidetable.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::VAS.Core.Catalog.GetString ("Duration");
			this.label6.UseMarkup = true;
			this.slidetable.Add (this.label6);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.slidetable [this.label6]));
			w6.XOptions = ((global::Gtk.AttachOptions)(0));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.slidetable);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.slidetable]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child VAS.UI.Dialog.EditPlaylistElementProperties.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 411;
			this.DefaultHeight = 110;
			this.Show ();
		}
	}
}
