
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Component
{
	public partial class HotKeyView
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Button hotKeyButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Component.HotKeyView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.Component.HotKeyView";
			// Container child VAS.UI.Component.HotKeyView.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hotKeyButton = new global::Gtk.Button ();
			this.hotKeyButton.CanFocus = true;
			this.hotKeyButton.Name = "hotKeyButton";
			this.hbox1.Add (this.hotKeyButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hotKeyButton]));
			w1.Position = 0;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
