
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Component
{
	public partial class LimitationWidget
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.EventBox limit_box;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label count_label;

		private global::Gtk.Label separator_label;

		private global::Gtk.Label limit_label;

		private global::Gtk.Button upgradeButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Component.LimitationWidget
			global::Stetic.BinContainer.Attach (this);
			this.HeightRequest = 24;
			this.Name = "VAS.UI.Component.LimitationWidget";
			// Container child VAS.UI.Component.LimitationWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.limit_box = new global::Gtk.EventBox ();
			this.limit_box.HeightRequest = 24;
			this.limit_box.Name = "limit_box";
			// Container child limit_box.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.HeightRequest = 24;
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.count_label = new global::Gtk.Label ();
			this.count_label.Name = "count_label";
			this.count_label.LabelProp = global::VAS.Core.Catalog.GetString ("-");
			this.hbox2.Add (this.count_label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.count_label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.separator_label = new global::Gtk.Label ();
			this.separator_label.Name = "separator_label";
			this.separator_label.LabelProp = global::VAS.Core.Catalog.GetString ("/");
			this.hbox2.Add (this.separator_label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.separator_label]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.limit_label = new global::Gtk.Label ();
			this.limit_label.Name = "limit_label";
			this.limit_label.LabelProp = global::VAS.Core.Catalog.GetString ("--");
			this.hbox2.Add (this.limit_label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.limit_label]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.upgradeButton = new global::Gtk.Button ();
			this.upgradeButton.WidthRequest = 24;
			this.upgradeButton.HeightRequest = 24;
			this.upgradeButton.CanFocus = true;
			this.upgradeButton.Name = "upgradeButton";
			this.upgradeButton.FocusOnClick = false;
			this.hbox2.Add (this.upgradeButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.upgradeButton]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.limit_box.Add (this.hbox2);
			this.vbox3.Add (this.limit_box);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.limit_box]));
			w6.Position = 0;
			w6.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
