
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI
{
	public partial class MainWindow
	{
		private global::Gtk.HBox centralBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.MainWindow
			this.Name = "VAS.UI.MainWindow";
			this.Title = global::VAS.Core.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child VAS.UI.MainWindow.Gtk.Container+ContainerChild
			this.centralBox = new global::Gtk.HBox ();
			this.centralBox.Name = "centralBox";
			this.centralBox.Spacing = 6;
			this.Add (this.centralBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
