
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Component
{
	public partial class DynamicButtonToolbarView
	{
		private global::Gtk.HBox hbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Component.DynamicButtonToolbarView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.Component.DynamicButtonToolbarView";
			// Container child VAS.UI.Component.DynamicButtonToolbarView.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
