
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Component
{
	public partial class HotkeysConfiguration
	{
		private global::Gtk.Table table;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Component.HotkeysConfiguration
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.Component.HotkeysConfiguration";
			// Container child VAS.UI.Component.HotkeysConfiguration.Gtk.Container+ContainerChild
			this.table = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(30));
			this.table.BorderWidth = ((uint)(20));
			this.Add (this.table);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
