
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI.Panel
{
	public partial class UpgradeLimitationPanel
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.VBox mainVBox;

		private global::Gtk.Alignment headersAlignment;

		private global::Gtk.VBox headersVBox;

		private global::Gtk.Label header;

		private global::Gtk.Label featuresHeader;

		private global::Gtk.Alignment featuresAlignment;

		private global::Gtk.VBox bodyVBox;

		private global::Gtk.Table featuresTable;

		private global::Gtk.VBox featuresVBox;

		private global::Gtk.Label featuresCaption;

		private global::Gtk.Fixed captionFixed;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.Panel.UpgradeLimitationPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VAS.UI.Panel.UpgradeLimitationPanel";
			// Container child VAS.UI.Panel.UpgradeLimitationPanel.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox ();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.mainVBox = new global::Gtk.VBox ();
			this.mainVBox.Name = "mainVBox";
			this.mainVBox.Spacing = 6;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.headersAlignment = new global::Gtk.Alignment (0F, 0.5F, 1F, 1F);
			this.headersAlignment.Name = "headersAlignment";
			this.headersAlignment.LeftPadding = ((uint)(75));
			this.headersAlignment.TopPadding = ((uint)(26));
			this.headersAlignment.RightPadding = ((uint)(75));
			// Container child headersAlignment.Gtk.Container+ContainerChild
			this.headersVBox = new global::Gtk.VBox ();
			this.headersVBox.Name = "headersVBox";
			this.headersVBox.Spacing = 10;
			// Container child headersVBox.Gtk.Box+BoxChild
			this.header = new global::Gtk.Label ();
			this.header.Name = "header";
			this.header.Xalign = 0F;
			this.header.LabelProp = global::VAS.Core.Catalog.GetString ("label1");
			this.headersVBox.Add (this.header);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.headersVBox [this.header]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child headersVBox.Gtk.Box+BoxChild
			this.featuresHeader = new global::Gtk.Label ();
			this.featuresHeader.Name = "featuresHeader";
			this.featuresHeader.Xalign = 0F;
			this.featuresHeader.LabelProp = global::VAS.Core.Catalog.GetString ("label3");
			this.headersVBox.Add (this.featuresHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.headersVBox [this.featuresHeader]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.headersAlignment.Add (this.headersVBox);
			this.mainVBox.Add (this.headersAlignment);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.headersAlignment]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.featuresAlignment = new global::Gtk.Alignment (0F, 0.5F, 1F, 1F);
			this.featuresAlignment.Name = "featuresAlignment";
			this.featuresAlignment.LeftPadding = ((uint)(120));
			this.featuresAlignment.TopPadding = ((uint)(10));
			this.featuresAlignment.RightPadding = ((uint)(120));
			this.featuresAlignment.BottomPadding = ((uint)(10));
			// Container child featuresAlignment.Gtk.Container+ContainerChild
			this.bodyVBox = new global::Gtk.VBox ();
			this.bodyVBox.Name = "bodyVBox";
			this.bodyVBox.Spacing = 10;
			// Container child bodyVBox.Gtk.Box+BoxChild
			this.featuresTable = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.featuresTable.Name = "featuresTable";
			this.featuresTable.RowSpacing = ((uint)(10));
			this.featuresTable.ColumnSpacing = ((uint)(10));
			this.bodyVBox.Add (this.featuresTable);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.bodyVBox [this.featuresTable]));
			w5.Position = 0;
			// Container child bodyVBox.Gtk.Box+BoxChild
			this.featuresVBox = new global::Gtk.VBox ();
			this.featuresVBox.Name = "featuresVBox";
			this.featuresVBox.Spacing = 10;
			this.bodyVBox.Add (this.featuresVBox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.bodyVBox [this.featuresVBox]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child bodyVBox.Gtk.Box+BoxChild
			this.featuresCaption = new global::Gtk.Label ();
			this.featuresCaption.Name = "featuresCaption";
			this.featuresCaption.Xalign = 1F;
			this.featuresCaption.LabelProp = global::VAS.Core.Catalog.GetString ("label5");
			this.featuresCaption.Justify = ((global::Gtk.Justification)(1));
			this.bodyVBox.Add (this.featuresCaption);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.bodyVBox [this.featuresCaption]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.featuresAlignment.Add (this.bodyVBox);
			this.mainVBox.Add (this.featuresAlignment);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.featuresAlignment]));
			w9.Position = 1;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.captionFixed = new global::Gtk.Fixed ();
			this.captionFixed.Name = "captionFixed";
			this.captionFixed.HasWindow = false;
			this.mainVBox.Add (this.captionFixed);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.captionFixed]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.eventbox.Add (this.mainVBox);
			this.Add (this.eventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
