
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI
{
	public partial class SliderView
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Button morebutton;

		private global::Gtk.Image moreButtonImage;

		private global::Gtk.VScale scale;

		private global::Gtk.Button lessbutton;

		private global::Gtk.Image lessButtonImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VAS.UI.SliderView
			this.WidthRequest = 30;
			this.HeightRequest = 205;
			this.Name = "VAS.UI.SliderView";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child VAS.UI.SliderView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.morebutton = new global::Gtk.Button ();
			this.morebutton.TooltipMarkup = "Pause";
			this.morebutton.WidthRequest = 25;
			this.morebutton.HeightRequest = 25;
			this.morebutton.Name = "morebutton";
			this.morebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child morebutton.Gtk.Container+ContainerChild
			this.moreButtonImage = new global::Gtk.Image ();
			this.moreButtonImage.WidthRequest = 22;
			this.moreButtonImage.HeightRequest = 22;
			this.moreButtonImage.Name = "moreButtonImage";
			this.morebutton.Add (this.moreButtonImage);
			this.vbox2.Add (this.morebutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.morebutton]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scale = new global::Gtk.VScale (null);
			this.scale.TooltipMarkup = "Playback speed";
			this.scale.Name = "scale";
			this.scale.UpdatePolicy = ((global::Gtk.UpdateType)(1));
			this.scale.Inverted = true;
			this.scale.Adjustment.Lower = 1;
			this.scale.Adjustment.Upper = 30;
			this.scale.Adjustment.PageIncrement = 3;
			this.scale.Adjustment.PageSize = 1;
			this.scale.Adjustment.StepIncrement = 1;
			this.scale.Adjustment.Value = 22;
			this.scale.DrawValue = true;
			this.scale.Digits = 0;
			this.scale.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox2.Add (this.scale);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scale]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lessbutton = new global::Gtk.Button ();
			this.lessbutton.TooltipMarkup = "Pause";
			this.lessbutton.WidthRequest = 25;
			this.lessbutton.HeightRequest = 25;
			this.lessbutton.Name = "lessbutton";
			this.lessbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child lessbutton.Gtk.Container+ContainerChild
			this.lessButtonImage = new global::Gtk.Image ();
			this.lessButtonImage.WidthRequest = 22;
			this.lessButtonImage.HeightRequest = 22;
			this.lessButtonImage.Name = "lessButtonImage";
			this.lessbutton.Add (this.lessButtonImage);
			this.vbox2.Add (this.lessbutton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lessbutton]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 30;
			this.DefaultHeight = 205;
			this.Hide ();
			this.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnFocusOutEvent);
		}
	}
}
