
// This file has been generated by the GUI designer. Do not modify.
namespace VAS.UI
{
	public partial class CapturerBin
	{
		private global::Gtk.VBox vbox1;

		private global::VAS.UI.VideoWindow videowindow;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HBox controllerbox;

		private global::Gtk.EventBox hourseventbox;

		private global::Gtk.Label hourlabel;

		private global::Gtk.Label label1;

		private global::Gtk.EventBox minuteseventbox;

		private global::Gtk.Label minuteslabel;

		private global::Gtk.Label label2;

		private global::Gtk.EventBox secondseventbox;

		private global::Gtk.Label secondslabel;

		private global::Gtk.Label periodlabel;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Button recbutton;

		private global::VAS.UI.Helpers.ImageView recimage;

		private global::Gtk.Button stopbutton;

		private global::VAS.UI.Helpers.ImageView stopimage;

		private global::Gtk.Button pausebutton;

		private global::VAS.UI.Helpers.ImageView pauseimage;

		private global::Gtk.Button resumebutton;

		private global::VAS.UI.Helpers.ImageView resumeimage;

		private global::Gtk.Button savebutton;

		private global::VAS.UI.Helpers.ImageView saveimage;

		private global::Gtk.Button cancelbutton;

		private global::VAS.UI.Helpers.ImageView cancelimage;

		private global::Gtk.VSeparator vseparator2;

		private global::Gtk.HBox lasteventbox;

		private global::Gtk.Label lastlabel;

		private global::Gtk.Button deletelastbutton;

		private global::VAS.UI.Helpers.ImageView deletelastimage;

		private global::Gtk.Button playlastbutton;

		private global::VAS.UI.Helpers.ImageView playlastimage;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget VAS.UI.CapturerBin
			global::Stetic.BinContainer.Attach(this);
			this.Name = "VAS.UI.CapturerBin";
			// Container child VAS.UI.CapturerBin.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.videowindow = new global::VAS.UI.VideoWindow();
			this.videowindow.Events = ((global::Gdk.EventMask)(256));
			this.videowindow.Name = "videowindow";
			this.videowindow.Ratio = 0F;
			this.vbox1.Add(this.videowindow);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.videowindow]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.controllerbox = new global::Gtk.HBox();
			this.controllerbox.Name = "controllerbox";
			this.controllerbox.Spacing = 6;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.hourseventbox = new global::Gtk.EventBox();
			this.hourseventbox.Name = "hourseventbox";
			// Container child hourseventbox.Gtk.Container+ContainerChild
			this.hourlabel = new global::Gtk.Label();
			this.hourlabel.Name = "hourlabel";
			this.hourlabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>00</b>");
			this.hourlabel.UseMarkup = true;
			this.hourseventbox.Add(this.hourlabel);
			this.controllerbox.Add(this.hourseventbox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.hourseventbox]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>:</b>");
			this.label1.UseMarkup = true;
			this.controllerbox.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.label1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.minuteseventbox = new global::Gtk.EventBox();
			this.minuteseventbox.Name = "minuteseventbox";
			// Container child minuteseventbox.Gtk.Container+ContainerChild
			this.minuteslabel = new global::Gtk.Label();
			this.minuteslabel.Name = "minuteslabel";
			this.minuteslabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>00</b>");
			this.minuteslabel.UseMarkup = true;
			this.minuteseventbox.Add(this.minuteslabel);
			this.controllerbox.Add(this.minuteseventbox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.minuteseventbox]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>:</b>");
			this.label2.UseMarkup = true;
			this.controllerbox.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.label2]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.secondseventbox = new global::Gtk.EventBox();
			this.secondseventbox.Name = "secondseventbox";
			// Container child secondseventbox.Gtk.Container+ContainerChild
			this.secondslabel = new global::Gtk.Label();
			this.secondslabel.Name = "secondslabel";
			this.secondslabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>00</b>");
			this.secondslabel.UseMarkup = true;
			this.secondseventbox.Add(this.secondslabel);
			this.controllerbox.Add(this.secondseventbox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.secondseventbox]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.periodlabel = new global::Gtk.Label();
			this.periodlabel.Name = "periodlabel";
			this.periodlabel.Xpad = 10;
			this.controllerbox.Add(this.periodlabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.periodlabel]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.controllerbox.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.vseparator1]));
			w11.Position = 6;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.recbutton = new global::Gtk.Button();
			this.recbutton.TooltipMarkup = "Start recording period";
			this.recbutton.CanFocus = true;
			this.recbutton.Name = "recbutton";
			this.recbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child recbutton.Gtk.Container+ContainerChild
			this.recimage = new global::VAS.UI.Helpers.ImageView();
			this.recimage.Name = "recimage";
			this.recimage.Xpad = 5;
			this.recimage.Ypad = 5;
			this.recbutton.Add(this.recimage);
			this.controllerbox.Add(this.recbutton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.recbutton]));
			w13.Position = 7;
			w13.Expand = false;
			w13.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.stopbutton = new global::Gtk.Button();
			this.stopbutton.TooltipMarkup = "Stop recording period";
			this.stopbutton.CanFocus = true;
			this.stopbutton.Name = "stopbutton";
			this.stopbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child stopbutton.Gtk.Container+ContainerChild
			this.stopimage = new global::VAS.UI.Helpers.ImageView();
			this.stopimage.Name = "stopimage";
			this.stopimage.Xpad = 5;
			this.stopimage.Ypad = 5;
			this.stopbutton.Add(this.stopimage);
			this.controllerbox.Add(this.stopbutton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.stopbutton]));
			w15.Position = 8;
			w15.Expand = false;
			w15.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.pausebutton = new global::Gtk.Button();
			this.pausebutton.TooltipMarkup = "Pause clock";
			this.pausebutton.CanFocus = true;
			this.pausebutton.Name = "pausebutton";
			this.pausebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child pausebutton.Gtk.Container+ContainerChild
			this.pauseimage = new global::VAS.UI.Helpers.ImageView();
			this.pauseimage.Name = "pauseimage";
			this.pauseimage.Xpad = 5;
			this.pauseimage.Ypad = 5;
			this.pausebutton.Add(this.pauseimage);
			this.controllerbox.Add(this.pausebutton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.pausebutton]));
			w17.Position = 9;
			w17.Expand = false;
			w17.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.resumebutton = new global::Gtk.Button();
			this.resumebutton.TooltipMarkup = "Resume clock";
			this.resumebutton.CanFocus = true;
			this.resumebutton.Name = "resumebutton";
			this.resumebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child resumebutton.Gtk.Container+ContainerChild
			this.resumeimage = new global::VAS.UI.Helpers.ImageView();
			this.resumeimage.Name = "resumeimage";
			this.resumeimage.Xpad = 5;
			this.resumeimage.Ypad = 5;
			this.resumebutton.Add(this.resumeimage);
			this.controllerbox.Add(this.resumebutton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.resumebutton]));
			w19.Position = 10;
			w19.Expand = false;
			w19.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.savebutton = new global::Gtk.Button();
			this.savebutton.TooltipMarkup = "Save project";
			this.savebutton.CanFocus = true;
			this.savebutton.Name = "savebutton";
			this.savebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child savebutton.Gtk.Container+ContainerChild
			this.saveimage = new global::VAS.UI.Helpers.ImageView();
			this.saveimage.Name = "saveimage";
			this.saveimage.Xpad = 5;
			this.saveimage.Ypad = 5;
			this.savebutton.Add(this.saveimage);
			this.controllerbox.Add(this.savebutton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.savebutton]));
			w21.Position = 11;
			w21.Expand = false;
			w21.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.cancelbutton = new global::Gtk.Button();
			this.cancelbutton.TooltipMarkup = "Cancel capture";
			this.cancelbutton.CanFocus = true;
			this.cancelbutton.Name = "cancelbutton";
			this.cancelbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child cancelbutton.Gtk.Container+ContainerChild
			this.cancelimage = new global::VAS.UI.Helpers.ImageView();
			this.cancelimage.Name = "cancelimage";
			this.cancelimage.Xpad = 5;
			this.cancelimage.Ypad = 5;
			this.cancelbutton.Add(this.cancelimage);
			this.controllerbox.Add(this.cancelbutton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.cancelbutton]));
			w23.Position = 12;
			w23.Expand = false;
			w23.Fill = false;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.Name = "vseparator2";
			this.controllerbox.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.vseparator2]));
			w24.Position = 13;
			// Container child controllerbox.Gtk.Box+BoxChild
			this.lasteventbox = new global::Gtk.HBox();
			this.lasteventbox.Name = "lasteventbox";
			this.lasteventbox.Spacing = 6;
			// Container child lasteventbox.Gtk.Box+BoxChild
			this.lastlabel = new global::Gtk.Label();
			this.lastlabel.Name = "lastlabel";
			this.lastlabel.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.lastlabel.MaxWidthChars = 15;
			this.lasteventbox.Add(this.lastlabel);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.lasteventbox[this.lastlabel]));
			w25.Position = 0;
			w25.Fill = false;
			// Container child lasteventbox.Gtk.Box+BoxChild
			this.deletelastbutton = new global::Gtk.Button();
			this.deletelastbutton.TooltipMarkup = "Delete event";
			this.deletelastbutton.CanFocus = true;
			this.deletelastbutton.Name = "deletelastbutton";
			this.deletelastbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child deletelastbutton.Gtk.Container+ContainerChild
			this.deletelastimage = new global::VAS.UI.Helpers.ImageView();
			this.deletelastimage.Name = "deletelastimage";
			this.deletelastimage.Xpad = 5;
			this.deletelastimage.Ypad = 5;
			this.deletelastbutton.Add(this.deletelastimage);
			this.lasteventbox.Add(this.deletelastbutton);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.lasteventbox[this.deletelastbutton]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child lasteventbox.Gtk.Box+BoxChild
			this.playlastbutton = new global::Gtk.Button();
			this.playlastbutton.TooltipMarkup = "Replay event";
			this.playlastbutton.CanFocus = true;
			this.playlastbutton.Name = "playlastbutton";
			this.playlastbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child playlastbutton.Gtk.Container+ContainerChild
			this.playlastimage = new global::VAS.UI.Helpers.ImageView();
			this.playlastimage.Name = "playlastimage";
			this.playlastimage.Xpad = 5;
			this.playlastimage.Ypad = 5;
			this.playlastbutton.Add(this.playlastimage);
			this.lasteventbox.Add(this.playlastbutton);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.lasteventbox[this.playlastbutton]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.controllerbox.Add(this.lasteventbox);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.controllerbox[this.lasteventbox]));
			w30.PackType = ((global::Gtk.PackType)(1));
			w30.Position = 14;
			w30.Expand = false;
			w30.Fill = false;
			this.alignment1.Add(this.controllerbox);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w32.Position = 1;
			w32.Expand = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.videowindow.Hide();
			this.Show();
		}
	}
}
