#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit". The hook auto adds new files
# to makefiles & to POTFILES.in and checks for whitespace errors.
# The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.
#
# To enable this hook, move this file to ".git/hooks/pre-commit"
# or symlink it.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

need_update=""
for i in `git diff --cached --name-only --diff-filter=A -- data`;do
	ret=`grep -l "$i" data/icons/Makefile.am || grep -l "$i" data/theme/Makefile.am`
	if [[ ! "$ret" ]];then
		echo "$i not in data/icons/Makefile.am or data/theme/Makefile.am. Calling update-data.py"
		need_update="true"
	fi
done
if [[ "$need_update" ]];then
	python tools/update-data.py .
fi

for i in `git diff --cached --name-only --diff-filter=A|grep ".cs$"`;do
        ret=`grep -l "^$i$" po/POTFILES.in`
        if [[ ! "$ret" ]];then
                echo "$i not in POTFILES.in. Adding it automatically"
                echo "$i" >> po/POTFILES.in
        fi
done
git add po/POTFILES.in

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against -- `git ls-files|grep -v "gtk-gui"`
